### PR TITLE
Fix compilation error building Npgsql 5 package

### PR DESCRIPTION
**Pull request by Plasma**
Fix reference to property (NpgsqlConnection.Settings) introduced in PR #252 that is not public in Npgsql v5

### CODE REVIEW

**Comment by Plasma** [comment]
@frankhommers Can you merge this one too to fix the final complilation error, this should then let AppVeyor CI build the Npgsql v5 package

**Comment by azygis** [comment]
I don't entirely like what I see at the moment. Doesn't it leave the v5 library in a possibly broken state? Shouldn't we check the connection string argument for it?

**Comment by Plasma** [comment]
Thanks @azygis thats a good point, I avoided doing the string check that was in a related PR as it felt brittle, but it was a good idea, I instead have pushed a change to parse the connection string using `NpgsqlConnectionStringBuilder` instead to check for `Enlist` under Npgsql 5, but for Npgsql 6, continue to use the `connection.Settings` property that holds this information.

**Comment by azygis** [comment]
Awesome, that was exactly what I suggested!

**Comment by azygis** [comment]
Well, it was still waiting for the last changes, but it's not really something blocking 😅 Thanks for the fixes!

**Comment by frankhommers** [comment]
@Plasma I have added you as collaborator as well.
I/We don't have specific rules. I added @vytautask as a first collaborator and then @azygis 
I liked their PR's and suggestions, just like I like yours.

**Comment by Plasma** [comment]
> @Plasma I have added you as collaborator as well.
> I/We don't have specific rules. I added @vytautask as a first collaborator and then @azygis
> I liked their PR's and suggestions, just like I like yours.

Thank you, I’ve accepted the invitation 😌
