### ISSUE TITLE
Support for Hangfire 1.4.0

### ISSUE THREAD

**Issue by nicolasguenther** [frankhommers/Hangfire.PostgreSql#12]
Are there any plans to support Hangfire 1.4.0?

**Comment by odinserj** [comment]
@nicolasguenther, do you have any problems with Hangfire 1.4 + Hangfire.PostgreSql 1.3.4?

**Comment by nicolasguenther** [comment]
No, i just read in the hangfire 1.4.0 release notes that the database schema changed. I was wondering if the PostgreSql plugin could handle the schema change.

**Comment by odinserj** [comment]
It relates to Hangfire.SqlServer only.

**Comment by nicolasguenther** [comment]
Thank you!

**Comment by nicolasguenther** [comment]
I found out that the PostgreSql plugin indeed doesn't work with Hangfire 1.4.0 because it isn't possible to configure the PostgreSql Storage anymore. The extension method `UsePostgreSqlStorage` is not available on the `GlobalConfiguration.Configuration` object and the `GlobalConfiguration.Configuration.UseStorage` method doesn't accept instances of `PostgreSqlStorage` anymore.

**Comment by odinserj** [comment]
> GlobalConfiguration.Configuration.UseStorage method doesn't accept instances of PostgreSqlStorage

What does "doesn't accept" mean? Compilation error? What is the message?

**Comment by barhun** [comment]
i don't know if it's is convenient to ask, but... is @frankhommers working on some other plugin and planning to drop support for this one?

**Comment by frankhommers** [comment]
@barhun No I won't drop support, I will continue to work on it. Currently I don't need it myself yet, so the priority is low for me right now. I think I'll need it soon, so that'll increase priority. I am happy to accept pull requests ;-)

**Comment by nicolasguenther** [comment]
I'm glad to hear that you will continue to work on it. The only real problem i found after some investigation is that Hangfire.PostgreSql doesn't support continuations yet.
